/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendeeProfile {
  'bio' : string,
  'displayName' : string,
  'interests' : Array<string>,
  'userId' : Principal,
  'badges' : Array<string>,
  'company' : string,
  'jobTitle' : string,
  'avatarUrl' : string,
  'points' : bigint,
}
export type BoothId = bigint;
export interface Event {
  'id' : EventId,
  'status' : string,
  'title' : string,
  'tags' : Array<string>,
  'description' : string,
  'bannerImage' : string,
  'streamUrl' : string,
  'hostId' : Principal,
  'startDate' : bigint,
  'eventType' : string,
}
export interface EventFeedback {
  'id' : FeedbackId,
  'eventId' : EventId,
  'userId' : Principal,
  'comment' : string,
  'rating' : bigint,
}
export type EventId = bigint;
export interface EventStats {
  'eventId' : EventId,
  'totalAttended' : bigint,
  'totalRegistered' : bigint,
  'engagementScore' : bigint,
}
export type FeedbackId = bigint;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'toUser' : Principal,
  'timestamp' : bigint,
  'fromUser' : Principal,
}
export type MessageId = string;
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
}
export type NotificationId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SponsorBooth {
  'id' : BoothId,
  'eventId' : EventId,
  'websiteUrl' : string,
  'tier' : string,
  'description' : string,
  'logoUrl' : string,
  'contactEmail' : string,
  'demoUrl' : string,
  'sponsorName' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type TicketId = bigint;
export interface TicketPurchase {
  'id' : TicketId,
  'eventId' : EventId,
  'tierId' : TierId,
  'purchasedAt' : bigint,
  'buyerId' : Principal,
  'stripeSessionId' : string,
}
export interface TicketTier {
  'id' : TierId,
  'eventId' : EventId,
  'name' : string,
  'sold' : bigint,
  'available' : bigint,
  'price' : bigint,
}
export type TierId = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBadge' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardPoints' : ActorMethod<[Principal, bigint], undefined>,
  'connectWithUser' : ActorMethod<[Principal], undefined>,
  'createBooth' : ActorMethod<[SponsorBooth], BoothId>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createEvent' : ActorMethod<[Event], EventId>,
  'createNotification' : ActorMethod<[Notification], NotificationId>,
  'createOrUpdateProfile' : ActorMethod<[AttendeeProfile], undefined>,
  'createTicketTier' : ActorMethod<[TicketTier], TierId>,
  'getAllBooths' : ActorMethod<[], Array<SponsorBooth>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getBoothsForEvent' : ActorMethod<[EventId], Array<SponsorBooth>>,
  'getCallerProfile' : ActorMethod<[], AttendeeProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [AttendeeProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getEventFeedback' : ActorMethod<[EventId], Array<EventFeedback>>,
  'getEventsByStatus' : ActorMethod<[string], Array<Event>>,
  'getLeaderboard' : ActorMethod<[], Array<[Principal, string, bigint]>>,
  'getMyConnections' : ActorMethod<[], Array<Principal>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyTickets' : ActorMethod<[], Array<TicketPurchase>>,
  'getProfile' : ActorMethod<[Principal], AttendeeProfile>,
  'getProfileByPrincipal' : ActorMethod<[Principal], AttendeeProfile>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTiersForEvent' : ActorMethod<[EventId], Array<TicketTier>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [AttendeeProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'purchaseTicket' : ActorMethod<[TierId, string], TicketId>,
  'saveCallerUserProfile' : ActorMethod<[AttendeeProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitFeedback' : ActorMethod<[EventFeedback], FeedbackId>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBooth' : ActorMethod<[SponsorBooth], undefined>,
  'updateEvent' : ActorMethod<[Event], undefined>,
  'updateEventStats' : ActorMethod<[EventStats], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];