/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BoothId = IDL.Nat;
export const EventId = IDL.Nat;
export const SponsorBooth = IDL.Record({
  'id' : BoothId,
  'eventId' : EventId,
  'websiteUrl' : IDL.Text,
  'tier' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
  'contactEmail' : IDL.Text,
  'demoUrl' : IDL.Text,
  'sponsorName' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : EventId,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'bannerImage' : IDL.Text,
  'streamUrl' : IDL.Text,
  'hostId' : IDL.Principal,
  'startDate' : IDL.Int,
  'eventType' : IDL.Text,
});
export const NotificationId = IDL.Nat;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const AttendeeProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'badges' : IDL.Vec(IDL.Text),
  'company' : IDL.Text,
  'jobTitle' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'points' : IDL.Nat,
});
export const TierId = IDL.Nat;
export const TicketTier = IDL.Record({
  'id' : TierId,
  'eventId' : EventId,
  'name' : IDL.Text,
  'sold' : IDL.Nat,
  'available' : IDL.Nat,
  'price' : IDL.Nat,
});
export const MessageId = IDL.Text;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'toUser' : IDL.Principal,
  'timestamp' : IDL.Int,
  'fromUser' : IDL.Principal,
});
export const FeedbackId = IDL.Nat;
export const EventFeedback = IDL.Record({
  'id' : FeedbackId,
  'eventId' : EventId,
  'userId' : IDL.Principal,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const TicketId = IDL.Nat;
export const TicketPurchase = IDL.Record({
  'id' : TicketId,
  'eventId' : EventId,
  'tierId' : TierId,
  'purchasedAt' : IDL.Int,
  'buyerId' : IDL.Principal,
  'stripeSessionId' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const EventStats = IDL.Record({
  'eventId' : EventId,
  'totalAttended' : IDL.Nat,
  'totalRegistered' : IDL.Nat,
  'engagementScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBadge' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardPoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'connectWithUser' : IDL.Func([IDL.Principal], [], []),
  'createBooth' : IDL.Func([SponsorBooth], [BoothId], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createEvent' : IDL.Func([Event], [EventId], []),
  'createNotification' : IDL.Func([Notification], [NotificationId], []),
  'createOrUpdateProfile' : IDL.Func([AttendeeProfile], [], []),
  'createTicketTier' : IDL.Func([TicketTier], [TierId], []),
  'getAllBooths' : IDL.Func([], [IDL.Vec(SponsorBooth)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getBoothsForEvent' : IDL.Func([EventId], [IDL.Vec(SponsorBooth)], ['query']),
  'getCallerProfile' : IDL.Func([], [AttendeeProfile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AttendeeProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getEventFeedback' : IDL.Func([EventId], [IDL.Vec(EventFeedback)], ['query']),
  'getEventsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getMyConnections' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyTickets' : IDL.Func([], [IDL.Vec(TicketPurchase)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [AttendeeProfile], ['query']),
  'getProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [AttendeeProfile],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTiersForEvent' : IDL.Func([EventId], [IDL.Vec(TicketTier)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AttendeeProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([NotificationId], [], []),
  'purchaseTicket' : IDL.Func([TierId, IDL.Text], [TicketId], []),
  'saveCallerUserProfile' : IDL.Func([AttendeeProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitFeedback' : IDL.Func([EventFeedback], [FeedbackId], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBooth' : IDL.Func([SponsorBooth], [], []),
  'updateEvent' : IDL.Func([Event], [], []),
  'updateEventStats' : IDL.Func([EventStats], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BoothId = IDL.Nat;
  const EventId = IDL.Nat;
  const SponsorBooth = IDL.Record({
    'id' : BoothId,
    'eventId' : EventId,
    'websiteUrl' : IDL.Text,
    'tier' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
    'contactEmail' : IDL.Text,
    'demoUrl' : IDL.Text,
    'sponsorName' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : EventId,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'bannerImage' : IDL.Text,
    'streamUrl' : IDL.Text,
    'hostId' : IDL.Principal,
    'startDate' : IDL.Int,
    'eventType' : IDL.Text,
  });
  const NotificationId = IDL.Nat;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const AttendeeProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'badges' : IDL.Vec(IDL.Text),
    'company' : IDL.Text,
    'jobTitle' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'points' : IDL.Nat,
  });
  const TierId = IDL.Nat;
  const TicketTier = IDL.Record({
    'id' : TierId,
    'eventId' : EventId,
    'name' : IDL.Text,
    'sold' : IDL.Nat,
    'available' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const MessageId = IDL.Text;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'toUser' : IDL.Principal,
    'timestamp' : IDL.Int,
    'fromUser' : IDL.Principal,
  });
  const FeedbackId = IDL.Nat;
  const EventFeedback = IDL.Record({
    'id' : FeedbackId,
    'eventId' : EventId,
    'userId' : IDL.Principal,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const TicketId = IDL.Nat;
  const TicketPurchase = IDL.Record({
    'id' : TicketId,
    'eventId' : EventId,
    'tierId' : TierId,
    'purchasedAt' : IDL.Int,
    'buyerId' : IDL.Principal,
    'stripeSessionId' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const EventStats = IDL.Record({
    'eventId' : EventId,
    'totalAttended' : IDL.Nat,
    'totalRegistered' : IDL.Nat,
    'engagementScore' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBadge' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardPoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'connectWithUser' : IDL.Func([IDL.Principal], [], []),
    'createBooth' : IDL.Func([SponsorBooth], [BoothId], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createEvent' : IDL.Func([Event], [EventId], []),
    'createNotification' : IDL.Func([Notification], [NotificationId], []),
    'createOrUpdateProfile' : IDL.Func([AttendeeProfile], [], []),
    'createTicketTier' : IDL.Func([TicketTier], [TierId], []),
    'getAllBooths' : IDL.Func([], [IDL.Vec(SponsorBooth)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getBoothsForEvent' : IDL.Func(
        [EventId],
        [IDL.Vec(SponsorBooth)],
        ['query'],
      ),
    'getCallerProfile' : IDL.Func([], [AttendeeProfile], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(AttendeeProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getEventFeedback' : IDL.Func(
        [EventId],
        [IDL.Vec(EventFeedback)],
        ['query'],
      ),
    'getEventsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Event)], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getMyConnections' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyTickets' : IDL.Func([], [IDL.Vec(TicketPurchase)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [AttendeeProfile], ['query']),
    'getProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [AttendeeProfile],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTiersForEvent' : IDL.Func([EventId], [IDL.Vec(TicketTier)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AttendeeProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([NotificationId], [], []),
    'purchaseTicket' : IDL.Func([TierId, IDL.Text], [TicketId], []),
    'saveCallerUserProfile' : IDL.Func([AttendeeProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitFeedback' : IDL.Func([EventFeedback], [FeedbackId], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBooth' : IDL.Func([SponsorBooth], [], []),
    'updateEvent' : IDL.Func([Event], [], []),
    'updateEventStats' : IDL.Func([EventStats], [], []),
  });
};

export const init = ({ IDL }) => { return []; };